web-ser

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -13,4 +13,12 @@ USERNAME=$3
 PATH_TO_SSH_KEY=$4
 
 # Transfer the file using scp with strict host key checking disabled
-scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"
+scp -i "$PATH_TO_SSH_KEY" -o "StrictHostKeyChecking=no" "$PATH_TO_FILE" "$PATH_TO_SSH_KEY" "$USERNAME@$SERVER_IP:~/"
+
+# checking if the transfer was successful
+if [$? -eq 0]
+then
+	echo "file was transfered successfully"
+else
+	echo "File transfer is failed"
+fi
